version: "3.4"

services:
  api:
    image: codeforacause/tuition-fond-irida-app:backend-#{TAG_NUMBER}#
    container_name: fond-irida-api
    ports:
      - 5069
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AppSettings__Contentful__DeliveryApiKey=#{DELIVERYAPIKEY}#
      - AppSettings__Contentful__PreviewApiKey=#{PREVIEWAPIKEY}#
      - AppSettings__Contentful__SpaceId=#{SPACEID}#
      - AppSettings__Contentful__Environment=content
      - AppSettings__EmailClient__FromEmailAddress=#{FROMEMAILADDRESS}#
      - AppSettings__EmailClient__FromEmailPassword=#{FROMEMAILPASSWORD}#
      - AppSettings__EmailClient__SmtpClient=smtp.gmail.com
    restart: always
  web:
    image: codeforacause/tuition-fond-irida-app:web-#{TAG_NUMBER}#
    container_name: fond-irida-web
    ports:
      - "25000:3000"
    environment:
      - REACT_APP_API_URL=https://api.fond-irida.codeforacause.rs
      - REACT_APP_CONTENTFUL_DELIVERY_ACCESS_KEY=#{DELIVERY_ACCESS_KEY}#
      - REACT_APP_CONTENTFUL_BASE_GRAPHQL_URL=https://graphql.contentful.com/content/v1/spaces/lpy11m2kyblz/environments/ui
    restart: always
