name: CI
on:
  push:
    branches:
      - main
jobs:
  Main_branch:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@main
      - name: Building docker image backend
        run: docker build ./TuitionFondIrida/ -t codeforacause/tuition-fond-irida-app:backend-${{ github.run_number }}
      - name: Building docker image web
        run: docker build ./webapp/ -t codeforacause/tuition-fond-irida-app:web-${{ github.run_number }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pushing docker image to CR backend
        run: docker push codeforacause/tuition-fond-irida-app:backend-${{ github.run_number }}
      - name: Pushing docker image to CR web
        run: docker push codeforacause/tuition-fond-irida-app:web-${{ github.run_number }}
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          files: '["**docker-compose.tuition-fond-irida-app.yaml"]'
        env:
          TAG_NUMBER: "${{ github.run_number }}"
          DeliveryApiKey: ${{ secrets.DeliveryApiKey }}
          PreviewApiKey: ${{ secrets.PreviewApiKey }}
          SpaceId: ${{ secrets.SpaceId }}
          FromEmailAddress: ${{ secrets.FromEmailAddress }}
          FromEmailPassword: ${{ secrets.FromEmailPassword }}
          DELIVERY_ACCESS_KEY: ${{ secrets.DELIVERY_ACCESS_KEY }}
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "docker-compose.tuition-fond-irida-app.yaml"
          target: "./Projects/tuition-fond-irida-app/"
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: docker-compose -f ./Projects/tuition-fond-irida-app/docker-compose.tuition-fond-irida-app.yaml up -d